<a href="https://colab.research.google.com/github/sedhamen-ctrl/retail-sales-analysis/blob/main/p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import zipfile
import os

zip_path = "/content/archive.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/dataset")

os.listdir("/content/dataset")

['retail_store_sales.csv']

In [ ]:
import pandas as pd

df = pd.read_csv("/content/dataset/retail_store_sales.csv")

print("Jumlah baris dan kolom:")
print(df.shape)

print("\nNama kolom:")
print(df.columns.tolist())

print("\n5 data pertama:")
display(df.head())

Jumlah baris dan kolom:
(12575, 11)

Nama kolom:
['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit', 'Quantity', 'Total Spent', 'Payment Method', 'Location', 'Transaction Date', 'Discount Applied']

5 data pertama:

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [ ]:
# 1. Informasi tipe data dan jumlah data
df.info()

# 2. Jumlah data kosong
print("\n=== DATA KOSONG ===")
print(df.isnull().sum())

# 3. Jumlah data duplikat
print("\n=== DUPLIKAT ===")
print("Jumlah baris duplikat:", df.duplicated().sum())
print("Transaction ID duplikat:", df["Transaction ID"].duplicated().sum())

# 4. Jumlah nilai unik
print("\n=== NILAI UNIK ===")
print(df.nunique())

# 5. Statistik angka
print("\n=== STATISTIK ===")
display(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

=== DATA KOSONG ===
Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

=== DUPLIKAT ===
Jumlah baris duplikat: 0
Transaction ID duplikat: 0

=== NILAI UNIK ===
Transaction ID      12575
Customer ID            25
Category                8
Item                  200
Price Per Unit         25
Quantity               10
Total Spent           227
Payment Method          3
Location                2
Transaction Date     1114
Discount Applied        2
dtype: int64

=== STATISTIK ===

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [ ]:
# Melihat nilai yang ada pada kolom-kolom kategorikal

for col in ['Category', 'Payment Method', 'Location', 'Discount Applied']:
    print(f"\n=== {col} ===")
    print(df[col].value_counts(dropna=False))

=== Category ===
Category
Electric household essentials         1591
Furniture                             1591
Food                                  1588
Milk Products                         1584
Butchers                              1568
Beverages                             1567
Computers and electric accessories    1558
Patisserie                            1528
Name: count, dtype: int64

=== Payment Method ===
Payment Method
Cash              4310
Digital Wallet    4144
Credit Card       4121
Name: count, dtype: int64

=== Location ===
Location
Online      6354
In-store    6221
Name: count, dtype: int64

=== Discount Applied ===
Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

In [ ]:
# Cek apakah Total Spent = Price Per Unit × Quantity

df['Calculated Total'] = df['Price Per Unit'] * df['Quantity']

print("Jumlah data yang bisa dibandingkan:",
      df[['Total Spent', 'Calculated Total']].dropna().shape[0])

print("\nContoh perbandingan:")
display(
    df[['Price Per Unit', 'Quantity', 'Total Spent', 'Calculated Total']]
    .dropna()
    .head(10)
)

Jumlah data yang bisa dibandingkan: 11362

Contoh perbandingan:

    Price Per Unit  Quantity  Total Spent  Calculated Total
0             18.5      10.0        185.0             185.0
1             29.0       9.0        261.0             261.0
2             21.5       2.0         43.0              43.0
3             27.5       9.0        247.5             247.5
4             12.5       7.0         87.5              87.5
6              5.0       8.0         40.0              40.0
8             27.5       1.0         27.5              27.5
9             36.5       3.0        109.5             109.5
10             8.0       9.0         72.0              72.0
12             6.5       7.0         45.5              45.5

In [ ]:
pd.crosstab(
    df['Discount Applied'].fillna('Missing'),
    df['Payment Method']
)

Payment Method    Cash  Credit Card  Digital Wallet
Discount Applied
False             1378         1359            1420
True              1459         1397            1363
Missing           1473         1365            1361

In [ ]:
pd.crosstab(
    df['Discount Applied'].fillna('Missing'),
    df['Location']
)

Location          In-store  Online
Discount Applied
False                 2055    2102
True                  2070    2149
Missing               2096    2103

In [ ]:
df.groupby('Discount Applied', dropna=False)[
    ['Price Per Unit', 'Quantity', 'Total Spent']
].mean()

                  Price Per Unit  Quantity  Total Spent
Discount Applied
False                  23.425711  5.580979   129.953330
True                   23.493377  5.533466   130.491043
NaN                    23.178768  5.494985   128.508651

In [ ]:
print("Missing berdasarkan kolom:")
display(df.isnull().sum())

print("\nPola missing:")
display(
    df.isnull()
      .groupby(['Item', 'Price Per Unit', 'Quantity', 'Total Spent'])
      .size()
      .sort_values(ascending=False)
      .head(15)
)

Missing berdasarkan kolom:

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
Calculated Total    1213
dtype: int64

Pola missing:

Item   Price Per Unit  Quantity  Total Spent
False  False           False     False          11362
True   True            False     False            609
       False           True      True             604
dtype: int64

In [ ]:
# Cek apakah Category + Price Per Unit bisa menentukan Item
item_mapping = (
    df.dropna(subset=['Item', 'Price Per Unit'])
      .groupby(['Category', 'Price Per Unit'])['Item']
      .nunique()
      .reset_index(name='Jumlah Item')
)

print("Kombinasi Category + Price yang hanya punya 1 Item:")
display(item_mapping[item_mapping['Jumlah Item'] == 1].head(20))

print("\nKombinasi Category + Price yang punya lebih dari 1 Item:")
display(item_mapping[item_mapping['Jumlah Item'] > 1].head(20))

Kombinasi Category + Price yang hanya punya 1 Item:

     Category  Price Per Unit  Jumlah Item
0   Beverages             5.0            1
1   Beverages             6.5            1
2   Beverages             8.0            1
3   Beverages             9.5            1
4   Beverages            11.0            1
5   Beverages            12.5            1
6   Beverages            14.0            1
7   Beverages            15.5            1
8   Beverages            17.0            1
9   Beverages            18.5            1
10  Beverages            20.0            1
11  Beverages            21.5            1
12  Beverages            23.0            1
13  Beverages            24.5            1
14  Beverages            26.0            1
15  Beverages            27.5            1
16  Beverages            29.0            1
17  Beverages            30.5            1
18  Beverages            32.0            1
19  Beverages            33.5            1

Kombinasi Category + Price yang punya lebih dari 1 Item:

Empty DataFrame
Columns: [Category, Price Per Unit, Jumlah Item]
Index: []

In [ ]:
print("Missing Item berdasarkan Category:")

missing_item = (
    df[df['Item'].isna()]
    .groupby('Category')
    .size()
    .sort_values(ascending=False)
)

display(missing_item)

Missing Item berdasarkan Category:

Category
Food                                  162
Computers and electric accessories    161
Milk Products                         159
Patisserie                            159
Electric household essentials         154
Butchers                              147
Beverages                             140
Furniture                             131
dtype: int64

In [ ]:
# Membuat mapping Category + Price -> Item
item_mapping = (
    df.dropna(subset=['Item', 'Price Per Unit'])
      .groupby(['Category', 'Price Per Unit'])['Item']
      .first()
)

# Cari baris yang Item-nya kosong tetapi Category dan Price tersedia
missing_item = df[
    df['Item'].isna() &
    df['Category'].notna() &
    df['Price Per Unit'].notna()
].copy()

# Coba cari Item berdasarkan Category + Price
missing_item['Predicted Item'] = missing_item.apply(
    lambda row: item_mapping.get(
        (row['Category'], row['Price Per Unit'])
    ),
    axis=1
)

print("Total Item missing:", df['Item'].isna().sum())
print("Bisa direcover:", missing_item['Predicted Item'].notna().sum())
print("Tidak bisa direcover:", missing_item['Predicted Item'].isna().sum())

display(missing_item.head(10))

Total Item missing: 1213
Bisa direcover: 604
Tidak bisa direcover: 0

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,Calculated Total,Predicted Item
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True,NaN,Item_20_FUR
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN,NaN,Item_14_BEV
19,TXN_4206593,CUST_01,Furniture,NaN,35.0,NaN,NaN,Digital Wallet,Online,2025-01-13,False,NaN,Item_21_FUR
25,TXN_3481599,CUST_05,Furniture,NaN,39.5,NaN,NaN,Cash,Online,2022-09-08,False,NaN,Item_24_FUR
34,TXN_1621497,CUST_06,Patisserie,NaN,23.0,NaN,NaN,Cash,In-store,2023-02-18,NaN,NaN,Item_13_PAT
83,TXN_4532214,CUST_25,Patisserie,NaN,15.5,NaN,NaN,Credit Card,In-store,2024-03-25,False,NaN,Item_8_PAT
112,TXN_5419965,CUST_23,Computers and electric accessories,NaN,20.0,NaN,NaN,Digital Wallet,Online,2024-01-16,False,NaN,Item_11_CEA
114,TXN_8210621,CUST_03,Beverages,NaN,39.5,NaN,NaN,Digital Wallet,Online,2024-01-03,False,NaN,Item_24_BEV
118,TXN_8586300,CUST_11,Computers and electric accessories,NaN,27.5,NaN,NaN,Credit Card,Online,2022-02-08,False,NaN,Item_16_CEA
138,TXN_1154680,CUST_25,Furniture,NaN,35.0,NaN,NaN,Credit Card,Online,2022-12-18,False,NaN,Item_21_FUR

In [ ]:
# Validasi mapping Item berdasarkan Category + Price

validation = df.dropna(subset=['Item', 'Price Per Unit']).copy()

# Harga yang seharusnya dimiliki setiap Item
item_price_check = (
    validation
    .groupby(['Category', 'Item'])['Price Per Unit']
    .nunique()
    .reset_index(name='Jumlah Harga')
)

print("Item yang memiliki lebih dari 1 harga:")
display(item_price_check[item_price_check['Jumlah Harga'] > 1])

Item yang memiliki lebih dari 1 harga:

Empty DataFrame
Columns: [Category, Item, Jumlah Harga]
Index: []

In [ ]:
# Isi Item yang kosong menggunakan hasil prediksi
df.loc[df['Item'].isna(), 'Item'] = missing_item['Predicted Item']

print("Sisa Item missing:", df['Item'].isna().sum())

Sisa Item missing: 609

In [ ]:
# Cek apakah setiap Item memiliki satu harga yang konsisten

price_check = (
    df.dropna(subset=['Item', 'Price Per Unit'])
      .groupby('Item')['Price Per Unit']
      .nunique()
)

print("Item dengan lebih dari 1 harga:")
display(price_check[price_check > 1])

print("\nJumlah Item yang memiliki harga konsisten:",
      (price_check == 1).sum())

Item dengan lebih dari 1 harga:

Series([], Name: Price Per Unit, dtype: int64)

Jumlah Item yang memiliki harga konsisten: 200

In [ ]:
# Buat mapping Item -> Price Per Unit
price_mapping = (
    df.dropna(subset=['Item', 'Price Per Unit'])
      .groupby('Item')['Price Per Unit']
      .first()
)

# Isi Price Per Unit yang kosong berdasarkan Item
df['Price Per Unit'] = df.apply(
    lambda row: price_mapping.get(row['Item'])
    if pd.isna(row['Price Per Unit']) else row['Price Per Unit'],
    axis=1
)

print("Sisa Price Per Unit yang missing:",
      df['Price Per Unit'].isna().sum())

Sisa Price Per Unit yang missing: 609

In [ ]:
# Cek pola missing Quantity dan Total Spent
quantity_total_check = df[
    df['Quantity'].isna() | df['Total Spent'].isna()
][['Item', 'Price Per Unit', 'Quantity', 'Total Spent']]

display(quantity_total_check.head(20))

print("Jumlah baris yang Quantity missing:",
      df['Quantity'].isna().sum())

print("Jumlah baris yang Total Spent missing:",
      df['Total Spent'].isna().sum())

print("\nPola missing:")
display(
    df[['Price Per Unit', 'Quantity', 'Total Spent']]
    .isna()
    .value_counts()
    .reset_index(name='Jumlah')
)

             Item  Price Per Unit  Quantity  Total Spent
7     Item_20_FUR            33.5       NaN          NaN
15    Item_14_BEV            24.5       NaN          NaN
19    Item_21_FUR            35.0       NaN          NaN
25    Item_24_FUR            39.5       NaN          NaN
34    Item_13_PAT            23.0       NaN          NaN
83     Item_8_PAT            15.5       NaN          NaN
112   Item_11_CEA            20.0       NaN          NaN
114   Item_24_BEV            39.5       NaN          NaN
118   Item_16_CEA            27.5       NaN          NaN
138   Item_21_FUR            35.0       NaN          NaN
139   Item_14_FUR            24.5       NaN          NaN
179   Item_13_BUT            23.0       NaN          NaN
182    Item_2_BEV             6.5       NaN          NaN
232  Item_18_FOOD            30.5       NaN          NaN
234   Item_23_EHE            38.0       NaN          NaN
253    Item_6_FUR            12.5       NaN          NaN
259  Item_11_FOOD            20.0       NaN          NaN
277   Item_19_CEA            32.0       NaN          NaN
292    Item_8_CEA            15.5       NaN          NaN
333   Item_9_FOOD            17.0       NaN          NaN

Jumlah baris yang Quantity missing: 604
Jumlah baris yang Total Spent missing: 604

Pola missing:

   Price Per Unit  Quantity  Total Spent  Jumlah
0           False     False        False   11362
1            True     False        False     609
2           False      True         True     604

In [ ]:
# Distribusi Quantity berdasarkan Item

quantity_pattern = (
    df.dropna(subset=['Item', 'Quantity'])
      .groupby('Item')['Quantity']
      .agg(['count', 'mean', 'median', 'min', 'max'])
      .sort_values('count', ascending=False)
)

display(quantity_pattern.head(20))

              count      mean  median  min   max
Item
Item_2_BEV      126  5.365079     5.0  1.0  10.0
Item_25_FUR     113  5.451327     6.0  1.0  10.0
Item_11_FUR     110  5.209091     5.0  1.0  10.0
Item_16_MILK    109  5.752294     6.0  1.0  10.0
Item_1_MILK     109  5.302752     5.0  1.0  10.0
Item_20_BUT     107  5.261682     5.0  1.0  10.0
Item_5_FUR      107  5.429907     5.0  1.0  10.0
Item_11_MILK    106  5.415094     5.0  1.0  10.0
Item_19_CEA     106  5.264151     5.0  1.0  10.0
Item_14_FOOD    106  5.339623     5.0  1.0  10.0
Item_19_MILK    105  5.609524     6.0  1.0  10.0
Item_24_FUR     105  5.104762     5.0  1.0  10.0
Item_8_EHE      105  5.161905     5.0  1.0  10.0
Item_12_CEA     101  5.594059     6.0  1.0  10.0
Item_13_FOOD    101  5.752475     6.0  1.0  10.0
Item_22_BUT     100  5.400000     5.5  1.0  10.0
Item_14_BEV     100  5.520000     5.0  1.0  10.0
Item_12_PAT     100  5.450000     5.0  1.0  10.0
Item_25_EHE      98  5.744898     6.0  1.0  10.0
Item_5_CEA       98  5.693878     6.0  1.0  10.0

In [ ]:
quantity_variation = (
    df.dropna(subset=['Item', 'Quantity'])
      .groupby('Item')['Quantity']
      .nunique()
)

print("Jumlah Item:", len(quantity_variation))
print("\nDistribusi jumlah variasi Quantity:")
display(quantity_variation.value_counts().sort_index())

Jumlah Item: 200

Distribusi jumlah variasi Quantity:

Quantity
3       1
4       4
5       1
6       6
7       4
8       8
9      13
10    163
Name: count, dtype: int64

In [ ]:
# Simpan data asli
df_raw = df.copy()

# Dataset untuk analisis
df_clean = df.dropna(
    subset=['Price Per Unit', 'Quantity', 'Total Spent']
).copy()

print("Data awal :", len(df_raw))
print("Data setelah cleaning :", len(df_clean))
print("Data yang dikeluarkan :", len(df_raw) - len(df_clean))

print("\nMissing setelah cleaning:")
display(df_clean.isnull().sum())

Data awal : 12575
Data setelah cleaning : 11362
Data yang dikeluarkan : 1213

Missing setelah cleaning:

Transaction ID         0
Customer ID            0
Category               0
Item                   0
Price Per Unit         0
Quantity               0
Total Spent            0
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    3783
Calculated Total       0
dtype: int64

In [ ]:
# Distribusi Discount Applied
print("Distribusi Discount Applied:")

display(
    df_clean['Discount Applied']
    .value_counts(dropna=False)
    .rename_axis('Discount Applied')
    .reset_index(name='Jumlah')
)

Distribusi Discount Applied:

  Discount Applied  Jumlah
0             True    3801
1              NaN    3783
2            False    3778

In [ ]:
# Bandingkan rata-rata transaksi berdasarkan status discount
display(
    df_clean.groupby(
        df_clean['Discount Applied'].fillna('Missing')
    )[['Price Per Unit', 'Quantity', 'Total Spent']]
    .mean()
)

                  Price Per Unit  Quantity  Total Spent
Discount Applied
False                  23.361302  5.587083   130.130360
True                   23.496054  5.527756   130.723625
Missing                23.212530  5.490352   128.069125

In [ ]:
# Ubah missing Discount Applied menjadi Unknown
df_clean['Discount Applied'] = (
    df_clean['Discount Applied']
    .fillna('Unknown')
    .astype(str)
)

# Cek hasil
print("Distribusi Discount Applied setelah cleaning:")

display(
    df_clean['Discount Applied']
    .value_counts()
    .rename_axis('Discount Applied')
    .reset_index(name='Jumlah')
)

Distribusi Discount Applied setelah cleaning:

  Discount Applied  Jumlah
0             True    3801
1          Unknown    3783
2            False    3778

In [ ]:
print("=== TIPE DATA ===")
print(df_clean.dtypes)

=== TIPE DATA ===
Transaction ID       object
Customer ID          object
Category             object
Item                 object
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
Discount Applied     object
Calculated Total    float64
dtype: object

In [ ]:
df_clean['Transaction Date'] = pd.to_datetime(
    df_clean['Transaction Date'],
    errors='coerce'
)

print(df_clean.dtypes)

Transaction ID              object
Customer ID                 object
Category                    object
Item                        object
Price Per Unit             float64
Quantity                   float64
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
Discount Applied            object
Calculated Total           float64
dtype: object

In [ ]:
print("Tanggal invalid:", df_clean['Transaction Date'].isna().sum())

Tanggal invalid: 0

In [ ]:
print("Tanggal paling awal :", df_clean['Transaction Date'].min())
print("Tanggal paling akhir:", df_clean['Transaction Date'].max())

Tanggal paling awal : 2022-01-01 00:00:00
Tanggal paling akhir: 2025-01-18 00:00:00

In [ ]:
print("=== CEK PRICE ===")
print("Harga <= 0:", (df_clean['Price Per Unit'] <= 0).sum())

print("\n=== CEK QUANTITY ===")
print("Quantity <= 0:", (df_clean['Quantity'] <= 0).sum())

=== CEK PRICE ===
Harga <= 0: 0

=== CEK QUANTITY ===
Quantity <= 0: 0

In [ ]:
df_clean['Calculated Total'] = (
    df_clean['Price Per Unit'] * df_clean['Quantity']
)

df_clean['Total Difference'] = (
    df_clean['Total Spent'] - df_clean['Calculated Total']
)

print(
    "Total transaksi yang tidak sesuai:",
    (df_clean['Total Difference'] != 0).sum()
)

In [ ]:
df_clean = df_clean.drop(columns=['Calculated Total'])

In [ ]:
print(df_clean.shape)
display(df_clean.head())

In [ ]:
df_clean['Year'] = df_clean['Transaction Date'].dt.year

df_clean['Month'] = df_clean['Transaction Date'].dt.month

df_clean['Month Name'] = df_clean['Transaction Date'].dt.month_name()

df_clean['Year-Month'] = (
    df_clean['Transaction Date']
    .dt.to_period('M')
    .astype(str)
)

df_clean['Day of Week'] = (
    df_clean['Transaction Date']
    .dt.day_name()
)

In [ ]:
df_clean['Day Type'] = df_clean['Transaction Date'].dt.dayofweek.apply(
    lambda x: 'Weekend' if x >= 5 else 'Weekday'
)

In [ ]:
print(df_clean.columns.tolist())
print(df_clean.shape)
display(df_clean.head())

In [ ]:
df_clean = df_clean.drop(columns=['Total Difference'])

In [ ]:
print("=== BUSINESS OVERVIEW ===")

total_revenue = df_clean['Total Spent'].sum()
total_transactions = df_clean['Transaction ID'].nunique()
total_customers = df_clean['Customer ID'].nunique()
total_quantity = df_clean['Quantity'].sum()
average_transaction = df_clean['Total Spent'].mean()

print(f"Total Revenue       : ${total_revenue:,.2f}")
print(f"Total Transactions  : {total_transactions:,}")
print(f"Total Customers     : {total_customers:,}")
print(f"Total Quantity Sold : {total_quantity:,.0f}")
print(f"Average Transaction : ${average_transaction:,.2f}")

In [ ]:
# ==========================================
# EDA 2 - CATEGORY & PRODUCT ANALYSIS
# ==========================================

# 1. Analisis berdasarkan kategori
category_analysis = (
    df_clean.groupby('Category')
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Quantity_Sold=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum')
    )
    .sort_values('Revenue', ascending=False)
    .reset_index()
)

print("=== ANALISIS KATEGORI ===")
display(category_analysis)


# 2. Top 10 produk berdasarkan quantity
top_products_quantity = (
    df_clean.groupby('Item')
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Quantity_Sold=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum')
    )
    .sort_values('Quantity_Sold', ascending=False)
    .head(10)
    .reset_index()
)

print("=== TOP 10 PRODUK BERDASARKAN QUANTITY ===")
display(top_products_quantity)


# 3. Top 10 produk berdasarkan revenue
top_products_revenue = (
    df_clean.groupby('Item')
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Quantity_Sold=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum')
    )
    .sort_values('Revenue', ascending=False)
    .head(10)
    .reset_index()
)

print("=== TOP 10 PRODUK BERDASARKAN REVENUE ===")
display(top_products_revenue)

In [ ]:
# ==========================================
# EDA 3 - TIME ANALYSIS
# ==========================================

monthly_analysis = (
    df_clean.groupby('Year-Month')
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Quantity_Sold=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum')
    )
    .reset_index()
    .sort_values('Year-Month')
)

print("=== MONTHLY SALES ANALYSIS ===")
display(monthly_analysis)

print("\n=== BULAN DENGAN REVENUE TERTINGGI ===")
display(
    monthly_analysis.loc[
        monthly_analysis['Revenue'].idxmax()
    ]
)

print("\n=== BULAN DENGAN REVENUE TERENDAH ===")
display(
    monthly_analysis.loc[
        monthly_analysis['Revenue'].idxmin()
    ]
)

In [ ]:
# ==========================================
# EDA 4 - LOCATION, PAYMENT & DISCOUNT
# ==========================================

# 1. ANALISIS LOCATION
location_analysis = (
    df_clean.groupby('Location')
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Quantity_Sold=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum')
    )
    .reset_index()
    .sort_values('Revenue', ascending=False)
)

print("=== LOCATION ANALYSIS ===")
display(location_analysis)


# 2. ANALISIS PAYMENT METHOD
payment_analysis = (
    df_clean.groupby('Payment Method')
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Quantity_Sold=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum')
    )
    .reset_index()
    .sort_values('Revenue', ascending=False)
)

print("\n=== PAYMENT METHOD ANALYSIS ===")
display(payment_analysis)


# 3. ANALISIS DISCOUNT
discount_analysis = (
    df_clean.groupby('Discount Applied')
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Quantity_Sold=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum'),
        Avg_Transaction=('Total Spent', 'mean')
    )
    .reset_index()
    .sort_values('Revenue', ascending=False)
)

print("\n=== DISCOUNT ANALYSIS ===")
display(discount_analysis)

In [ ]:
# ==========================================
# EDA 5 - CROSS ANALYSIS
# ==========================================

# 1. Revenue berdasarkan Category + Location
category_location = (
    df_clean.groupby(['Category', 'Location'])
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Quantity_Sold=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum')
    )
    .reset_index()
    .sort_values('Revenue', ascending=False)
)

print("=== CATEGORY × LOCATION ===")
display(category_location)


# 2. Revenue berdasarkan Category + Discount
category_discount = (
    df_clean.groupby(['Category', 'Discount Applied'])
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Revenue=('Total Spent', 'sum'),
        Avg_Transaction=('Total Spent', 'mean')
    )
    .reset_index()
    .sort_values('Revenue', ascending=False)
)

print("\n=== CATEGORY × DISCOUNT ===")
display(category_discount)


# 3. Top product berdasarkan revenue dan quantity
product_performance = (
    df_clean.groupby(['Item', 'Category'])
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Quantity_Sold=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum')
    )
    .reset_index()
)

# Tambahkan ranking
product_performance['Revenue_Rank'] = (
    product_performance['Revenue']
    .rank(method='dense', ascending=False)
)

product_performance['Quantity_Rank'] = (
    product_performance['Quantity_Sold']
    .rank(method='dense', ascending=False)
)

print("\n=== PRODUCT PERFORMANCE ===")
display(
    product_performance
    .sort_values('Revenue', ascending=False)
    .head(15)
)

In [ ]:
# ============================================================
# RETAIL SALES ANALYSIS - PROFESSIONAL EDA VISUALIZATION
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

# ------------------------------------------------------------
# FORMATTER
# ------------------------------------------------------------

def rupiah(x, pos):
    return f'${x/1000:.0f}K'

currency_formatter = FuncFormatter(rupiah)


# ============================================================
# 1. MONTHLY REVENUE TREND
# ============================================================

monthly = (
    df_clean.groupby('Year-Month')
    .agg(
        Revenue=('Total Spent', 'sum'),
        Transactions=('Transaction ID', 'nunique')
    )
    .reset_index()
)

# Cari bulan tertinggi & terendah
max_month = monthly.loc[monthly['Revenue'].idxmax()]
min_month = monthly.loc[monthly['Revenue'].idxmin()]

plt.figure(figsize=(15, 6))

plt.plot(
    monthly['Year-Month'],
    monthly['Revenue'],
    marker='o',
    linewidth=2
)

# Highlight highest
plt.scatter(
    max_month['Year-Month'],
    max_month['Revenue'],
    s=100,
    zorder=5
)

plt.annotate(
    f"Highest\n{max_month['Year-Month']}\n${max_month['Revenue']:,.0f}",
    xy=(max_month['Year-Month'], max_month['Revenue']),
    xytext=(0, 25),
    textcoords='offset points',
    ha='center',
    fontsize=10
)

plt.title(
    'Monthly Revenue Trend',
    fontsize=16,
    fontweight='bold'
)

plt.xlabel('Month')
plt.ylabel('Revenue')

plt.gca().yaxis.set_major_formatter(currency_formatter)

plt.xticks(
    range(0, len(monthly), 3),
    monthly['Year-Month'].iloc[::3],
    rotation=45
)

plt.grid(axis='y', alpha=0.25)

plt.tight_layout()
plt.show()


# ============================================================
# 2. REVENUE BY CATEGORY
# ============================================================

category = (
    df_clean.groupby('Category')
    .agg(
        Revenue=('Total Spent', 'sum'),
        Quantity=('Quantity', 'sum'),
        Transactions=('Transaction ID', 'nunique')
    )
    .sort_values('Revenue', ascending=True)
)

plt.figure(figsize=(11, 7))

bars = plt.barh(
    category.index,
    category['Revenue']
)

plt.title(
    'Revenue by Product Category',
    fontsize=16,
    fontweight='bold'
)

plt.xlabel('Revenue')
plt.ylabel('Category')

plt.gca().xaxis.set_major_formatter(currency_formatter)

# Label nilai
for bar in bars:
    width = bar.get_width()

    plt.text(
        width + 2000,
        bar.get_y() + bar.get_height()/2,
        f'${width:,.0f}',
        va='center',
        fontsize=9
    )

plt.grid(axis='x', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 3. TOP 10 PRODUCTS BY REVENUE
# ============================================================

top_products = (
    df_clean.groupby('Item')
    .agg(
        Revenue=('Total Spent', 'sum'),
        Quantity=('Quantity', 'sum')
    )
    .sort_values('Revenue', ascending=False)
    .head(10)
    .sort_values('Revenue')
)

plt.figure(figsize=(11, 7))

bars = plt.barh(
    top_products.index,
    top_products['Revenue']
)

plt.title(
    'Top 10 Products by Revenue',
    fontsize=16,
    fontweight='bold'
)

plt.xlabel('Revenue')
plt.ylabel('Product')

plt.gca().xaxis.set_major_formatter(currency_formatter)

for bar in bars:
    width = bar.get_width()

    plt.text(
        width + 300,
        bar.get_y() + bar.get_height()/2,
        f'${width:,.0f}',
        va='center',
        fontsize=9
    )

plt.grid(axis='x', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 4. TOP 10 PRODUCTS BY QUANTITY
# ============================================================

top_quantity = (
    df_clean.groupby('Item')
    .agg(
        Quantity=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum')
    )
    .sort_values('Quantity', ascending=False)
    .head(10)
    .sort_values('Quantity')
)

plt.figure(figsize=(11, 7))

bars = plt.barh(
    top_quantity.index,
    top_quantity['Quantity']
)

plt.title(
    'Top 10 Products by Quantity Sold',
    fontsize=16,
    fontweight='bold'
)

plt.xlabel('Units Sold')
plt.ylabel('Product')

for bar in bars:
    width = bar.get_width()

    plt.text(
        width + 10,
        bar.get_y() + bar.get_height()/2,
        f'{width:,.0f}',
        va='center',
        fontsize=9
    )

plt.grid(axis='x', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 5. ONLINE VS IN-STORE
# ============================================================

location = (
    df_clean.groupby('Location')
    .agg(
        Revenue=('Total Spent', 'sum'),
        Transactions=('Transaction ID', 'nunique'),
        Quantity=('Quantity', 'sum')
    )
    .reset_index()
)

plt.figure(figsize=(8, 6))

bars = plt.bar(
    location['Location'],
    location['Revenue']
)

plt.title(
    'Revenue by Sales Channel',
    fontsize=16,
    fontweight='bold'
)

plt.xlabel('Sales Channel')
plt.ylabel('Revenue')

plt.gca().yaxis.set_major_formatter(currency_formatter)

for bar in bars:
    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 10000,
        f'${height:,.0f}',
        ha='center',
        fontweight='bold'
    )

plt.grid(axis='y', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 6. PAYMENT METHOD
# ============================================================

payment = (
    df_clean.groupby('Payment Method')['Total Spent']
    .sum()
    .sort_values(ascending=False)
)

plt.figure(figsize=(9, 6))

bars = plt.bar(
    payment.index,
    payment.values
)

plt.title(
    'Revenue by Payment Method',
    fontsize=16,
    fontweight='bold'
)

plt.xlabel('Payment Method')
plt.ylabel('Revenue')

plt.gca().yaxis.set_major_formatter(currency_formatter)

for bar in bars:
    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 5000,
        f'${height:,.0f}',
        ha='center',
        fontweight='bold'
    )

plt.grid(axis='y', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 7. CATEGORY: REVENUE VS QUANTITY
# ============================================================

category_scatter = (
    df_clean.groupby('Category')
    .agg(
        Revenue=('Total Spent', 'sum'),
        Quantity=('Quantity', 'sum')
    )
    .reset_index()
)

plt.figure(figsize=(10, 7))

plt.scatter(
    category_scatter['Quantity'],
    category_scatter['Revenue'],
    s=120
)

for _, row in category_scatter.iterrows():

    plt.annotate(
        row['Category'],
        (
            row['Quantity'],
            row['Revenue']
        ),
        xytext=(5, 5),
        textcoords='offset points',
        fontsize=9
    )

plt.title(
    'Category Performance: Quantity vs Revenue',
    fontsize=16,
    fontweight='bold'
)

plt.xlabel('Quantity Sold')
plt.ylabel('Revenue')

plt.gca().yaxis.set_major_formatter(currency_formatter)

plt.grid(alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 8. DISCOUNT ANALYSIS
# ============================================================

discount = (
    df_clean.groupby('Discount Applied')
    .agg(
        Revenue=('Total Spent', 'sum'),
        Transactions=('Transaction ID', 'nunique'),
        Avg_Transaction=('Total Spent', 'mean')
    )
    .reset_index()
)

plt.figure(figsize=(8, 6))

bars = plt.bar(
    discount['Discount Applied'].astype(str),
    discount['Revenue']
)

plt.title(
    'Revenue by Discount Status',
    fontsize=16,
    fontweight='bold'
)

plt.xlabel('Discount Status')
plt.ylabel('Revenue')

plt.gca().yaxis.set_major_formatter(currency_formatter)

for bar in bars:
    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 5000,
        f'${height:,.0f}',
        ha='center',
        fontweight='bold'
    )

plt.grid(axis='y', alpha=0.2)

plt.tight_layout()
plt.show()

NameError: name 'df_clean' is not defined

In [ ]:
# ============================================================
# EDA LANJUTAN - RETAIL SALES ANALYSIS
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1. DISTRIBUSI TOTAL SPENT
# ============================================================

print("=== DISTRIBUSI TOTAL SPENT ===")

print(df_clean['Total Spent'].describe())

plt.figure(figsize=(10, 6))

plt.hist(
    df_clean['Total Spent'],
    bins=30,
    edgecolor='black'
)

plt.title(
    'Distribution of Transaction Value',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Total Spent')
plt.ylabel('Number of Transactions')

plt.grid(axis='y', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 2. DISTRIBUSI QUANTITY
# ============================================================

print("=== DISTRIBUSI QUANTITY ===")

print(df_clean['Quantity'].describe())

plt.figure(figsize=(9, 5))

quantity_counts = df_clean['Quantity'].value_counts().sort_index()

plt.bar(
    quantity_counts.index.astype(str),
    quantity_counts.values
)

plt.title(
    'Distribution of Quantity per Transaction',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Quantity')
plt.ylabel('Number of Transactions')

plt.grid(axis='y', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 3. OUTLIER TOTAL SPENT - IQR METHOD
# ============================================================

print("=== OUTLIER TOTAL SPENT ===")

Q1 = df_clean['Total Spent'].quantile(0.25)
Q3 = df_clean['Total Spent'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df_clean[
    (df_clean['Total Spent'] < lower_bound) |
    (df_clean['Total Spent'] > upper_bound)
]

print(f"Q1              : {Q1:.2f}")
print(f"Q3              : {Q3:.2f}")
print(f"IQR             : {IQR:.2f}")
print(f"Lower Bound     : {lower_bound:.2f}")
print(f"Upper Bound     : {upper_bound:.2f}")
print(f"Jumlah Outlier  : {len(outliers)}")

display(
    outliers[
        [
            'Transaction ID',
            'Customer ID',
            'Category',
            'Item',
            'Price Per Unit',
            'Quantity',
            'Total Spent'
        ]
    ]
    .sort_values('Total Spent', ascending=False)
    .head(20)
)


# ============================================================
# 4. BOXPLOT TOTAL SPENT
# ============================================================

plt.figure(figsize=(10, 4))

plt.boxplot(
    df_clean['Total Spent'],
    vert=False
)

plt.title(
    'Boxplot of Transaction Value',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Total Spent')

plt.grid(axis='x', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 5. CUSTOMER PERFORMANCE
# ============================================================

customer_analysis = (
    df_clean.groupby('Customer ID')
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Total_Spent=('Total Spent', 'sum'),
        Quantity=('Quantity', 'sum'),
        Avg_Transaction=('Total Spent', 'mean')
    )
    .sort_values('Total_Spent', ascending=False)
    .reset_index()
)

print("=== TOP 10 CUSTOMER BERDASARKAN TOTAL SPENDING ===")

display(
    customer_analysis.head(10)
)


# ============================================================
# 6. CUSTOMER PALING SERING TRANSAKSI
# ============================================================

top_customers_transaction = (
    customer_analysis
    .sort_values('Transactions', ascending=False)
    .head(10)
)

plt.figure(figsize=(10, 6))

plt.barh(
    top_customers_transaction['Customer ID'],
    top_customers_transaction['Transactions']
)

plt.gca().invert_yaxis()

plt.title(
    'Top 10 Customers by Number of Transactions',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Number of Transactions')
plt.ylabel('Customer')

plt.grid(axis='x', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 7. CUSTOMER TOTAL SPENDING
# ============================================================

top_customers_spending = (
    customer_analysis
    .sort_values('Total_Spent', ascending=False)
    .head(10)
    .sort_values('Total_Spent')
)

plt.figure(figsize=(10, 6))

plt.barh(
    top_customers_spending['Customer ID'],
    top_customers_spending['Total_Spent']
)

plt.title(
    'Top 10 Customers by Total Spending',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Total Spending')
plt.ylabel('Customer')

plt.grid(axis='x', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 8. REPEAT CUSTOMER ANALYSIS
# ============================================================

customer_analysis['Customer Type'] = np.where(
    customer_analysis['Transactions'] > 1,
    'Repeat Customer',
    'One-time Customer'
)

customer_type = (
    customer_analysis['Customer Type']
    .value_counts()
)

print("=== CUSTOMER TYPE ===")
print(customer_type)

plt.figure(figsize=(7, 5))

plt.bar(
    customer_type.index,
    customer_type.values
)

plt.title(
    'Customer Type Distribution',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Customer Type')
plt.ylabel('Number of Customers')

plt.grid(axis='y', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 9. WEEKDAY VS WEEKEND
# ============================================================

day_analysis = (
    df_clean.groupby('Day Type')
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Quantity=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum'),
        Avg_Transaction=('Total Spent', 'mean')
    )
    .reset_index()
)

print("=== WEEKDAY VS WEEKEND ===")

display(day_analysis)


# Revenue
plt.figure(figsize=(7, 5))

plt.bar(
    day_analysis['Day Type'],
    day_analysis['Revenue']
)

plt.title(
    'Revenue: Weekday vs Weekend',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Day Type')
plt.ylabel('Revenue')

plt.grid(axis='y', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 10. REVENUE PER DAY OF WEEK
# ============================================================

weekday_order = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday'
]

weekday_analysis = (
    df_clean.groupby('Day of Week')['Total Spent']
    .sum()
    .reindex(weekday_order)
)

plt.figure(figsize=(10, 5))

plt.plot(
    weekday_analysis.index,
    weekday_analysis.values,
    marker='o',
    linewidth=2
)

plt.title(
    'Revenue by Day of Week',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Day')
plt.ylabel('Revenue')

plt.xticks(rotation=30)

plt.grid(alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 11. PRICE VS QUANTITY
# ============================================================

price_quantity = (
    df_clean.groupby('Price Per Unit')
    .agg(
        Avg_Quantity=('Quantity', 'mean'),
        Total_Quantity=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum')
    )
    .reset_index()
)

plt.figure(figsize=(10, 6))

plt.scatter(
    price_quantity['Price Per Unit'],
    price_quantity['Avg_Quantity'],
    s=80
)

plt.title(
    'Price vs Average Quantity per Transaction',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Price Per Unit')
plt.ylabel('Average Quantity')

plt.grid(alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 12. QUANTITY VS TOTAL SPENT
# ============================================================

plt.figure(figsize=(10, 6))

plt.scatter(
    df_clean['Quantity'],
    df_clean['Total Spent'],
    alpha=0.25
)

plt.title(
    'Quantity vs Transaction Value',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Quantity')
plt.ylabel('Total Spent')

plt.grid(alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 13. KORELASI NUMERIK
# ============================================================

numeric_cols = [
    'Price Per Unit',
    'Quantity',
    'Total Spent'
]

correlation = df_clean[numeric_cols].corr()

print("=== CORRELATION MATRIX ===")

display(correlation)


# Visualisasi correlation sederhana

plt.figure(figsize=(7, 5))

plt.imshow(
    correlation,
    interpolation='nearest'
)

plt.colorbar()

plt.xticks(
    range(len(correlation.columns)),
    correlation.columns,
    rotation=30
)

plt.yticks(
    range(len(correlation.columns)),
    correlation.columns
)

plt.title(
    'Correlation Matrix',
    fontsize=15,
    fontweight='bold'
)

# Tambahkan nilai korelasi
for i in range(len(correlation)):
    for j in range(len(correlation.columns)):
        plt.text(
            j,
            i,
            f"{correlation.iloc[i, j]:.2f}",
            ha='center',
            va='center'
        )

plt.tight_layout()
plt.show()


# ============================================================
# 14. REVENUE PER TAHUN
# ============================================================

year_analysis = (
    df_clean.groupby('Year')
    .agg(
        Transactions=('Transaction ID', 'nunique'),
        Quantity=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum'),
        Avg_Transaction=('Total Spent', 'mean')
    )
    .reset_index()
)

print("=== YEARLY PERFORMANCE ===")

display(year_analysis)


# ============================================================
# 15. PERTUMBUHAN REVENUE TAHUNAN
# ============================================================

year_analysis['Revenue Growth (%)'] = (
    year_analysis['Revenue']
    .pct_change()
    * 100
)

print("=== REVENUE GROWTH ===")

display(
    year_analysis[
        [
            'Year',
            'Revenue',
            'Revenue Growth (%)'
        ]
    ]
)


# ============================================================
# 16. REVENUE TAHUNAN
# ============================================================

plt.figure(figsize=(9, 5))

plt.bar(
    year_analysis['Year'].astype(str),
    year_analysis['Revenue']
)

plt.title(
    'Annual Revenue',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Year')
plt.ylabel('Revenue')

plt.grid(axis='y', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 17. AVERAGE TRANSACTION PER CATEGORY
# ============================================================

category_aov = (
    df_clean.groupby('Category')['Total Spent']
    .mean()
    .sort_values(ascending=True)
)

plt.figure(figsize=(10, 6))

plt.barh(
    category_aov.index,
    category_aov.values
)

plt.title(
    'Average Transaction Value by Category',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Average Transaction Value')
plt.ylabel('Category')

plt.grid(axis='x', alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 18. PRODUK: REVENUE VS QUANTITY
# ============================================================

product_analysis = (
    df_clean.groupby(['Item', 'Category'])
    .agg(
        Quantity=('Quantity', 'sum'),
        Revenue=('Total Spent', 'sum'),
        Transactions=('Transaction ID', 'nunique'),
        Avg_Price=('Price Per Unit', 'mean')
    )
    .reset_index()
)

plt.figure(figsize=(11, 7))

plt.scatter(
    product_analysis['Quantity'],
    product_analysis['Revenue'],
    s=60,
    alpha=0.6
)

plt.title(
    'Product Performance: Quantity vs Revenue',
    fontsize=15,
    fontweight='bold'
)

plt.xlabel('Total Quantity Sold')
plt.ylabel('Total Revenue')

plt.grid(alpha=0.2)

plt.tight_layout()
plt.show()


# ============================================================
# 19. PRODUK DENGAN REVENUE TINGGI TAPI QUANTITY RENDAH
# ============================================================

product_analysis['Revenue_per_Unit'] = (
    product_analysis['Revenue']
    / product_analysis['Quantity']
)

high_value_products = (
    product_analysis
    .sort_values('Revenue_per_Unit', ascending=False)
    .head(10)
)

print("=== TOP 10 PRODUCT BERDASARKAN REVENUE PER UNIT ===")

display(
    high_value_products[
        [
            'Item',
            'Category',
            'Quantity',
            'Revenue',
            'Revenue_per_Unit'
        ]
    ]
)


# ============================================================
# 20. SUMMARY EDA
# ============================================================

print("=" * 60)
print("SUMMARY EDA")
print("=" * 60)

print(f"Total Revenue          : ${df_clean['Total Spent'].sum():,.2f}")
print(f"Total Transactions     : {df_clean['Transaction ID'].nunique():,}")
print(f"Total Customers        : {df_clean['Customer ID'].nunique():,}")
print(f"Total Quantity Sold    : {df_clean['Quantity'].sum():,}")
print(f"Average Transaction    : ${df_clean['Total Spent'].mean():,.2f}")

print("\nKategori Revenue Tertinggi:")
print(
    df_clean.groupby('Category')['Total Spent']
    .sum()
    .idxmax()
)

print("\nProduk Revenue Tertinggi:")
print(
    df_clean.groupby('Item')['Total Spent']
    .sum()
    .idxmax()
)

print("\nProduk Quantity Tertinggi:")
print(
    df_clean.groupby('Item')['Quantity']
    .sum()
    .idxmax()
)

print("\nChannel Revenue Tertinggi:")
print(
    df_clean.groupby('Location')['Total Spent']
    .sum()
    .idxmax()
)